package kz.trei.office.structure;

public enum DepartmentType {
	ACCOUNTANCY,
	RESEARCH_AND_DEVELOPMENT,
	COMMERCIAL,
	WAREHOUSE,
	ASSEMBLY,
	PRODUCTION,
	ENGINEERING,
	METROLOGICAL_SERVICE,
	VERIFICATION_LABORATORY,
	ADMINISTRATIVE_SERVICE_UTILITY,
	NONE;
}
