package kz.trei.office.structure;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "position")
@XmlEnum
public enum PositionType {
	GENERAL_DIRECTOR,
	COMMERCIAL_DIRECTOR,
	DEPARTMENT_HEAD,
	SECRETARY_ADVISER,
	TECHNICAL_DIRECTOR,
	SYSTEM_ADMINISTRATOR,
	CHIEF_ACCOUNTANT,
	DEPUTY_CHIEF_ACCOUNTANT,
	ACCOUNTANT_MATERIALISTS,
	HR_ADMINISTRATION,
	WAREHOUSE_MANAGER,
	EQUIPMENT_ENGINEER,
	ADMINISTRATIVE_SERVICE_UTILITY_MANAGER,
	DRIVER,
	SECURITY_GUARD,
	JANITOR,
	ENGINEER,
	SOFTWARE_ENGINEER,
	SENIOR_SOFTWARE_ENGINEER,
	LEAD_SOFTWARE_ENGINEER,
	COMMISSIONING_ENGINEER,
	APCS_ENGINEER,
	LEAD_APCS_ENGINEER,
	LEAD_DESIGNER,
	DESIGN_ENGINEER,
	ELECTRONICS_ENGINEER,
	SENIOR_ELECTRONICS_ENGINEER,
	CHIEF_METROLOGIST,
	ENGINEER_METROLOGIST,
	CONSTRUCTION_ELECTRICIAN;
}
